apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "sulfoxide-bromine.fullname-with-suffix" (dict "arg" (printf "%s-%s" .Values.rootSecret.name "doppler") "root" .) }}
  labels: {{- include "sulfoxide-bromine.labels" . | nindent 4 }}
  annotations: {{- include "sulfoxide-bromine.annotations" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: {{ .Values.rootSecret.store.kind }}
    name: {{ .Values.rootSecret.store.name }}
  target:
    name: {{ template "sulfoxide-bromine.fullname-with-suffix" (dict "arg" .Values.rootSecret.name "root" .) }}
  data:
    - secretKey: {{ .Values.rootSecret.key.clientId }}
      remoteRef:
        key: {{ .Values.rootSecret.ref.clientId}}
    - secretKey: {{ .Values.rootSecret.key.clientSecret }}
      remoteRef:
        key: {{ .Values.rootSecret.ref.clientSecret}}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: "{{ .Values.storeName }}"
  labels: {{- include "sulfoxide-bromine.labels" . | nindent 4 }}
  annotations: {{- include "sulfoxide-bromine.annotations" . | nindent 4 }}
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: {{ .Values.rootSecret.key.clientId}}
            name: {{ template "sulfoxide-bromine.fullname-with-suffix" (dict "arg" .Values.rootSecret.name "root" .) }}
          clientSecret:
            key: {{ .Values.rootSecret.key.clientSecret}}
            name: {{ template "sulfoxide-bromine.fullname-with-suffix" (dict "arg" .Values.rootSecret.name "root" .) }}
      secretsScope:
        projectSlug: {{ .Values.serviceTree.platform }}-{{ .Values.serviceTree.service}}
        environmentSlug: {{ .Values.serviceTree.landscape}}
        secretsPath: /
      hostAPI: {{ .Values.infisicalHost }}